name: OpenFOAM Simulation

on:
  push:
    paths:
      - 'OpenFOAM/case/constant/transportProperties' # 파일이 업데이트될 때만 실행

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    container: openfoam/openfoam10-graphical-user-interface # 사용하시는 버전에 맞게 수정

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OpenFOAM Case
        run: |
          cd OpenFOAM/case
          ./Allrun # 또는 직접 blockMesh, simpleFoam 등 명령어 입력
