name: OpenFOAM PimpleFoam Simulation

on:
  push:
    branches: [ "main" ]  # 메인에 푸시될 때마다 실행
  workflow_dispatch:      # [Actions] 탭에서 버튼으로 수동 실행 가능하게 함

jobs:
  run-sim:
    runs-on: ubuntu-latest
    container: 
      image: opencfd/openfoam-run:2312
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install ParaView (for pvpython)
        run: |
          apt-get update
          apt-get install -y paraview

      - name: Run OpenFOAM and Post-processing
        shell: bash  # bash 명시
        run: |
          source /opt/openfoam10/etc/bashrc
          ./Allrun

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: flow-results
          path: OpenFOAM/case/screenshots/
